# Handling Missing Values
1. Replace :- In Pandas, the replace() method is used to substitute existing values within a DataFrame or Series with new values.
2. Interpolate :- The interpolate() method in Pandas is used to fill missing values (NaN) in a DataFrame or Series using various interpolation techniques.

# 1. Replace

In [6]:
import pandas as pd

var = pd.read_csv("CSV_files\\8Worldwide_Protests.csv")
var

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.0,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,NaN,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,NaN,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,NaN,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.0,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.0,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,NaN,10000.0,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.0,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,NaN,NaN,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,NaN,1000.0,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,NaN,NaN,Partial clampdown / state control

## to_replace parameter :- used for what to replace with what

In [12]:
var.replace(to_replace="USA", value="United States")

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,United States,Kent State shootings,2000,4.0,9.0,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,NaN,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,NaN,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,NaN,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.0,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.0,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,United States,George Floyd / BLM protests,15_000_000-26_000_000,NaN,10000.0,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.0,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,NaN,NaN,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,NaN,1000.0,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,NaN,NaN,Partial clampdown / state control

In [18]:
# without to_replace parameter

var.replace(["Nepal", "UK", "Greece"], "N")

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.0,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,NaN,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,NaN,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,NaN,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.0,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.0,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,NaN,10000.0,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,N,Gen Z social-media ban protests,thousands (est.),72.0,2113.0,Social media ban & corruption,PM resignation
8,1992.0,N,NaN,NaN,NaN,NaN,Economic / political,Policing and arrests
9,2008.0,N,Athens anti-austerity protests,hundreds_of_thousands,NaN,1000.0,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,NaN,NaN,Partial clampdown / state control

## regex parameter :- regular expression

In [24]:
var.replace("[A-Za-z]", "pk", regex=True)

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,pkpkpk,pkpkpkpk pkpkpkpkpk pkpkpkpkpkpkpkpkpk,2000,4.0,9.0,pkpkpkpk-pkpkpk (pkpkpkpkpkpkpkpk/pkpkpkpkpk p...,pkpkpkpkpkpkpkpk pkpkpkpkpk pkpkpkpk pkpkpkpk
1,1980.0,pkpkpkpkpkpk,pkpkpkpkpkpk / pkpkpkpkpkpkpkpkpkpk pkpkpkpkpk...,10000+,0.0,NaN,pkpkpkpkpk pkpkpkpkpkpk / pkpkpkpkpkpkpkpkpkpk...,pkpkpkpkpkpkpkpkpkpk pkpk pkpkpkpkpkpkpk pkpkp...
2,1989.0,pkpkpkpkpk,pkpkpkpkpkpkpkpkpk pkpkpkpkpkpk pkpkpkpkpkpkpkpk,pkpkpkpkpkpkpkpk_pkpk_pkpkpkpkpkpkpkpkpk,300.0,NaN,pkpkpk-pkpkpkpkpkpkpkpkpk / pkpkpkpkpkpkpkpkpk...,pkpkpkpkpkpkpkpk pkpkpkpkpkpkpkpkpk
3,2011.0,pkpkpkpkpk,pkpkpkpkpkpkpkpk pkpkpkpkpkpkpkpkpkpk (pkpkpkp...,pkpkpkpkpkpkpkpk,302.0,NaN,pkpkpkpk-pkpkpkpkpkpkpkpkpkpk / pkpkpkpkpkpkpk...,pkpkpkpkpkpk pkpkpk pkpkpkpkpkpkpkpk pkpkpkpkp...
4,2014.0,pkpkpkpk pkpkpkpk,pkpkpkpkpkpkpkpk pkpkpkpkpkpkpkpk (pkpkpkpk pk...,pkpkpkpk_pkpk_pkpkpkpkpkpkpkpkpk,0.0,200.0,pkpkpkpkpkpkpkpkpk pkpkpkpkpkpkpkpk / pkpkpkpk...,pkpkpkpkpkpk pkpkpkpkpkpkpkpkpk pkpkpk pkpkpkp...
5,2019.0,pkpkpkpkpk,pkpkpkpkpk pkpkpkpkpkpk pkpkpkpkpkpkpkpk,"1,000,000+",30.0,2300.0,pkpkpkpkpkpkpkpkpkpk / pkpkpkpk pkpk pkpkpkpkpkpk,"pkpkpkpkpk pkpk pkpkpkpkpkpkpkpkpk, pkpkpkpkpk..."
6,2020.0,pkpkpk,pkpkpkpkpkpk pkpkpkpkpk / pkpkpk pkpkpkpkpkpkpkpk,15_000_000-26_000_000,NaN,10000.0,pkpkpkpkpkpk pkpkpkpkpkpkpkpkpk / pkpkpkpkpkpk...,pkpkpkpkpkpk/pkpkpkpkpkpkpkpk pkpkpkpkpkpkpkpk...
7,2025.0,pkpkpkpkpk,pkpkpk pk pkpkpkpkpkpk-pkpkpkpkpk pkpkpk pkpkp...,pkpkpkpkpkpkpkpkpk (pkpkpk.),72.0,2113.0,pkpkpkpkpkpk pkpkpkpkpk pkpkpk & pkpkpkpkpkpkp...,pkpk pkpkpkpkpkpkpkpkpkpkpk
8,1992.0,pkpk,NaN,NaN,NaN,NaN,pkpkpkpkpkpkpkpk / pkpkpkpkpkpkpkpkpk,pkpkpkpkpkpkpkpk pkpkpk pkpkpkpkpkpkpk
9,2008.0,pkpkpkpkpkpk,pkpkpkpkpkpk pkpkpkpk-pkpkpkpkpkpkpkpkpk pkpkp...,pkpkpkpkpkpkpkpk_pkpk_pkpkpkpkpkpkpkpkpk,NaN,1000.0,pkpkpkpkpkpkpkpkpk pkpkpkpkpkpkpkpk / pkpkpk p...,"pkpkpkpk pkpkpkpkpkpk, pkpkpkpkpkpkpkpk pkpkpk..."
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1991.0,pkpkpkpkpkpk,1991 pkpkpkpkpkpk pkpkpkpk pkpkpkpkpkpkpkpk,NaN,2.0,NaN,NaN,pkpkpkpkpkpkpk pkpkpkpkpkpkpkpkpk / pkpkpkpkpk...

## Replace using dictionary

In [27]:
var.replace({"Country":"[A-Z]"}, 22, regex=True)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_5904\2728576359.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  var.replace({"Country":"[A-Z]"}, 22, regex=True)

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,22.0,Kent State shootings,2000,4.0,9.0,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,22.0,Gdansk / Solidarity strikes,10000+,0.0,NaN,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,22.0,Tiananmen Square protests,hundreds_of_thousands,300.0,NaN,Pro-democracy / political reform,Military crackdown
3,2011.0,22.0,Egyptian Revolution (Tahrir),millions,302.0,NaN,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,22.0,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.0,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,22.0,Chile Social Outburst,"1,000,000+",30.0,2300.0,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,22.0,George Floyd / BLM protests,15_000_000-26_000_000,NaN,10000.0,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,22.0,Gen Z social-media ban protests,thousands (est.),72.0,2113.0,Social media ban & corruption,PM resignation
8,1992.0,22.0,NaN,NaN,NaN,NaN,Economic / political,Policing and arrests
9,2008.0,22.0,Athens anti-austerity protests,hundreds_of_thousands,NaN,1000.0,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1991.0,22.0,1991 August Coup protests,NaN,2.0,NaN,NaN,Partial clampdown / state control

## inplace parameter -> directly replace in the original dataset
- var.replace(value_to_replace, method="ffill", inplace=True) ---> This will replace the value_to_replace with the ffill in the original dataset.

# 2. Interpolate
- The interpolate() method in Pandas is used to fill missing values (NaN) in a DataFrame or Series using various interpolation techniques.
- Note: If we are directly using Interplate function then it will work only with the number

In [44]:
var

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.0,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,NaN,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,NaN,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,NaN,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.0,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.0,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,NaN,10000.0,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.0,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,NaN,NaN,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,NaN,1000.0,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,NaN,NaN,Partial clampdown / state control

In [53]:
var.interpolate() # It is showing error because it only work with number not with alphabet
# And it will linearly change the data

C:\Users\KIIT\AppData\Local\Temp\ipykernel_5904\822220371.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate() # It is showing error because it only work with number not with alphabet

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.00,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,56.75,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,104.50,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,152.25,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.00,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.00,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,51.0,10000.00,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.00,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,54.5,1556.50,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,37.0,1000.00,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,1999.5,NaN,NaN,NaN,19.5,1000.00,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,1000.00,NaN,Partial clampdown / state control

## method:{'linear','time','index','values','nearest','zero','slinear','quadratic','cubic','barycentric','krogh','polynomial','spline','piecewise_polynomial','from_derivatives','pchip','akima'}

In [56]:
var.interpolate(method="index")

C:\Users\KIIT\AppData\Local\Temp\ipykernel_5904\2293714732.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(method="index")

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.00,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,56.75,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,104.50,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,152.25,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.00,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.00,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,51.0,10000.00,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.00,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,54.5,1556.50,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,37.0,1000.00,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,1999.5,NaN,NaN,NaN,19.5,1000.00,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,1000.00,NaN,Partial clampdown / state control

## axis parameter :- axis=0 works with columns wise

In [61]:
var.interpolate(method="index", axis=0) # error because it works with numerical value

C:\Users\KIIT\AppData\Local\Temp\ipykernel_5904\93173741.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(method="index", axis=0) # error because it works with numerical value

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.00,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,56.75,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,104.50,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,152.25,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.00,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.00,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,51.0,10000.00,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.00,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,54.5,1556.50,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,37.0,1000.00,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,1999.5,NaN,NaN,NaN,19.5,1000.00,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,1000.00,NaN,Partial clampdown / state control

## limit parameter :- fills data only upto limit

In [64]:
var.interpolate(limit=2)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_5904\545238221.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit=2)

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.00,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,56.75,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,104.50,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,NaN,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.00,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.00,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,51.0,10000.00,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.00,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,54.5,1556.50,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,37.0,1000.00,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,1999.5,NaN,NaN,NaN,NaN,1000.00,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,1000.00,NaN,Partial clampdown / state control

## limit_direction :- used to fill data in the direction
- forward
- backward
- both

In [76]:
var
var.interpolate(limit_direction="forward", limit=2)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_5904\308762534.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_direction="forward", limit=2)

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.00,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,56.75,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,104.50,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,NaN,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.00,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.00,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,51.0,10000.00,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.00,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,54.5,1556.50,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,37.0,1000.00,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,1999.5,NaN,NaN,NaN,NaN,1000.00,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,1000.00,NaN,Partial clampdown / state control

## limit_area parameter :- says either we want to use interpolate or not by specifying area
- limit_area = "inside"  ==> Fills the blank data
- limit_area = "outside" ==> Puts the NaN value

In [84]:
var.interpolate(limit_area = "inside") # Fills the blank data

C:\Users\KIIT\AppData\Local\Temp\ipykernel_5904\122193168.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_area = "inside") # Fills the blank data

,Year,Country,Protest_Name,Estimated_Participants,Deaths,Injuries,Cause,Government_Response
0,1970.0,USA,Kent State shootings,2000,4.0,9.00,Anti-war (Cambodia/Nixon policy),National Guard open fire
1,1980.0,Poland,Gdansk / Solidarity strikes,10000+,0.0,56.75,Labor rights / Solidarity movement,Imposition of martial law later (1981)
2,1989.0,China,Tiananmen Square protests,hundreds_of_thousands,300.0,104.50,Pro-democracy / political reform,Military crackdown
3,2011.0,Egypt,Egyptian Revolution (Tahrir),millions,302.0,152.25,Anti-government / overthrow Mubarak,"Police and military clashes, crackdown"
4,2014.0,Hong Kong,Umbrella Movement (Hong Kong),tens_of_thousands,0.0,200.00,Universal suffrage / democracy,Police clearance and arrests
5,2019.0,Chile,Chile Social Outburst,"1,000,000+",30.0,2300.00,Inequality / cost of living,"State of emergency, curfews, heavy policing"
6,2020.0,USA,George Floyd / BLM protests,15_000_000-26_000_000,51.0,10000.00,Police brutality / racial justice,"Police/military deployments, some crackdowns"
7,2025.0,Nepal,Gen Z social-media ban protests,thousands (est.),72.0,2113.00,Social media ban & corruption,PM resignation
8,1992.0,UK,NaN,NaN,54.5,1556.50,Economic / political,Policing and arrests
9,2008.0,Greece,Athens anti-austerity protests,hundreds_of_thousands,37.0,1000.00,Austerity measures / IMF policies,"Riot police, forceful dispersal"
10,1999.5,NaN,NaN,NaN,19.5,NaN,NaN,NaN
11,1991.0,Russia,1991 August Coup protests,NaN,2.0,NaN,NaN,Partial clampdown / state control